extends:
  - react-app # Add CRA configuration
  - eslint:recommended # Disables eslint rules conflicting with prettier
  - airbnb
  - airbnb/hooks
  - plugin:prettier/recommended # Enables prettier rules (should always be last)

ignorePatterns:
  - node_modules

rules:
  'import/extensions': 0
  'import/imports-first': [error, absolute-first]
  'import/newline-after-import': error
  'import/no-unresolved': 0
  'import/prefer-default-export': 0
  'jsx-a11y/anchor-is-valid': 0
  'max-classes-per-file': 0
  'no-console': 0
  'no-param-reassign': 0
  'no-return-assign': 0
  'no-shadow': 0
  'no-undef': 0
  'no-unused-vars': 0
  'no-use-before-define': 0
  'react/jsx-filename-extension': 0
  'react/jsx-indent': 0
  'react/jsx-one-expression-per-line': 0
  'react/no-unused-prop-types': 0
  'no-underscore-dangle': [error, { allow: ['_id', '__REDUX_DEVTOOLS_EXTENSION_COMPOSE__'] }]
  'react/jsx-props-no-spreading': 0
  'react/jsx-wrap-multilines': 0
  'react/destructuring-assignment': 0
  'react/prop-types': 0
  'padding-line-between-statements':
    - error
    - { blankLine: always, prev: '*', next: return }
    - { blankLine: always, prev: block-like, next: '*' }
  'import/order':
    - error
    - groups: [builtin, external, internal, parent, sibling, index]
      pathGroupsExcludedImportTypes: [builtin]
      pathGroups:
        - {
            pattern: '{actions,assets,components,contexts,epics,hooks,models,pages,reducers,services,shared,store,utils}/**',
            group: internal,
          }
        - {
            pattern: '{actions,assets,components,contexts,epics,hooks,models,pages,reducers,services,shared,store,utils}',
            group: internal,
          }
  'react/require-default-props': 0
  'no-redeclare': 'off'
  'no-plusplus': 'off'
  'quotes': ['error', 'single', { avoidEscape: true }]
  'jsx-a11y/click-events-have-key-events': 'off'
  'jsx-a11y/no-noninteractive-element-interactions': 'off'
  'react/jsx-no-script-url': 'off'
  'no-script-url': 'off'
  'jsx-a11y/label-has-associated-control': 'off'
  'jsx-a11y/no-static-element-interactions': 'off'
  'jsx-a11y/control-has-associated-label': 'off'
  'jsx-a11y/anchor-has-content': 'off'
  'no-continue': 'off'
  'no-nested-ternary': 'off'
