extends:
  - eslint:recommended
  - plugin:node/recommended
  - airbnb-base
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins: ['promise', 'import']
env:
  node: true
  es6: true
globals:
  expect: true
  it: true
  describe: true
  beforeAll: true
rules:
  'curly': error
  'import/imports-first': [error, absolute-first]
  'import/newline-after-import': error
  'no-alert': error
  'no-else-return': error
  'no-eval': error
  'no-lone-blocks': error
  'no-loop-func': error
  'no-magic-numbers': [0, { ignoreArrayIndexes: true, enforceConst: true }]
  'no-shadow': 0
  'no-unneeded-ternary': error
  'no-var': error
  'padding-line-between-statements':
    - error
    - { blankLine: always, prev: '*', next: return }
    - { blankLine: always, prev: block-like, next: '*' }
  'prefer-const': error
  'quotes': ['error', 'single', { avoidEscape: true }]
  'no-param-reassign': 0
  'no-useless-escape': 0
  'no-underscore-dangle': [2, { 'allow': ['_id', '_source', '_changed', '_previousDataValues', '_dataValues', '__'] }]
  'prefer-destructuring': 0
  'no-iterator': 1
  'no-restricted-syntax': ['error', 'LabeledStatement', 'WithStatement']
  'consistent-return': 0
  'comma-dangle': 0
  'guard-for-in': 0
  'object-curly-newline': ['error', { 'minProperties': 2, 'multiline': true }]
  'indent': [2, 2, { 'SwitchCase': 2 }]
  'radix': 0
  'object-shorthand': 1
  'newline-per-chained-call': [1, { 'ignoreChainWithDepth': 3 }]
  'no-confusing-arrow': 'error'
  'import/extensions': 0
  'no-mixed-operators': 2
  'class-methods-use-this': 0
  'no-console': ['error', { 'allow': ['warn', 'error'] }]
  'no-unused-vars':
    [
      'error',
      { 'vars': 'all', 'args': 'after-used', 'varsIgnorePattern': '[(colors|models)]', 'ignoreRestSiblings': false },
    ]
  'max-len': ['error', { 'code': 150, 'ignoreUrls': true }]
  'promise/no-return-wrap': 'warn'
  'promise/param-names': 'warn'
  'promise/no-native': 'off'
  'promise/no-nesting': 1
  'promise/no-promise-in-callback': 'warn'
  'promise/no-callback-in-promise': 'warn'
  'promise/avoid-new': 0
  'promise/no-new-statics': 'warn'
  'promise/no-return-in-finally': 'warn'
  'promise/valid-params': 'warn'
  'max-lines-per-function': ['warn', 500]
  'max-lines': ['error', { max: 1500, skipComments: true }]
  'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }]
  'no-await-in-loop': 0
  'max-classes-per-file': 0
  'no-plusplus': 0
  'no-promise-executor-return': 0
  'promise/always-return': 0
  'no-trailing-spaces': 'error'
  'no-useless-rename': 'error'
  'no-useless-return': 'error'
  'spaced-comment': ['error', 'always', { markers: ['/'] }]
  'no-lonely-if': 'error'

overrides:
  - files: ['*.js']
    extends:
      - plugin:prettier/recommended # Enables prettier rules (should always be last)
